apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/priority: "500"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://localhost:30080/"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "http://localhost:30080/prometheus/"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /prometheus(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: prometheus-service
            port:
              number: 9090
      - path: /query
        pathType: Prefix
        backend:
          service:
            name: prometheus-service
            port:
              number: 9090
